# Applications
# cask 'notunes'
cask 'suspicious-package'

# Fonts
cask 'font-fira-code'
# cask 'font-maple-mono'
# cask 'font-monaspace'

# Files & Search
brew 'bat'
brew 'eza'
brew 'fd'
brew 'fzy'
brew 'pipe-rename'
brew 'rg'
brew 'wget'

# Images & Video
brew 'ffmpeg'
brew 'imagemagick'
brew 'yt-dlp'

# Development
brew 'git'
brew 'httpie'
brew 'lazygit'
brew 'mise'
brew 'shellcheck'

# ruby-build
brew 'autoconf'
brew 'gmp'
brew 'libyaml'
brew 'openssl@3'
brew 'readline'

# System
brew 'duti'
brew 'htop'
