tap 'jonof/kenutils'

# Applications
cask 'notunes'

# Fonts
cask 'font-fira-code'

# QuickLook
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'suspicious-package'

# Shell
brew 'zsh'
brew 'eza'
brew 'fzy'
brew 'shellcheck'

# Images/Videos
brew 'ffmpeg'
brew 'imagemagick'
brew 'yt-dlp'
# brew 'mkvtoolnix'

# Miscellaneous
brew 'ack'
brew 'bat'
# brew 'bfg'
brew 'duti'
brew 'git'
brew 'git-absorb'
brew 'htop'
brew 'httpie'
brew 'mise'
brew 'rename'
brew 'rg'
brew 'wget'
# brew 'wrk'
