tap 'caskroom/cask'
tap 'homebrew/cask-fonts'
tap 'jonof/kenutils'

# Applications
cask 'aerial'

# Fonts
cask 'font-fira-code'
cask 'font-source-code-pro'

# QuickLook
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'suspicious-package'

# Dev: Go
brew 'go'

# Shell
brew 'zsh'
brew 'shellcheck'
brew 'fzy'

# Images/Videos
brew 'ffmpeg'
brew 'graphviz'
brew 'guetzli'
brew 'imagemagick'
brew 'jonof/kenutils/pngout'
brew 'jpegoptim'
brew 'optipng'
brew 'pngcrush'
brew 'pngquant'
brew 'youtube-dl'

# Miscellaneous
brew 'ack'
brew 'bat'
# brew 'bfg'
brew 'git'
brew 'htop'
brew 'httpie'
# brew 'tmux'
brew 'wget'
# brew 'wrk'
