---
include:
  - "**/*.rb"
exclude:
  - dotbot/**/*
  - dotbot-aptget/**/*
  - dotbot-brew/**/*
  - node-build/**/*
  - nodenv/**/*
  - rbenv/**/*
  - ruby-build/**/*
  - zplug/**/*
reporters:
  - all!
