[tools]
node = "lts"
ruby = "latest"
usage = "latest"
"npm:diff-so-fancy" = "latest"
"npm:pnpm" = "latest"
"npm:svgo" = "latest"
"gem:image_optim" = "latest"
"gem:image_optim_pack" = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "3d"
python.uv_venv_auto = "create|source"
