[settings]
# Since npm installs are currently experimental
# https://mise.jdx.dev/dev-tools/backends/npm.html
experimental = true

[env]
MISE_NODE_COREPACK = 'true'

[tools]
node = "lts"
ruby = "latest"
"npm:diff-so-fancy" = "latest"
