#!/usr/bin/env bash

[ -d /usr/share/fonts/opentype ] || sudo mkdir /usr/share/fonts/opentype
git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/opentype/scp
fc-cache -f -v
