#!/usr/bin/env zsh

# Scripts only have access to stuff in zshenv, so this is a hack for Dotbot
source "${HOME}/.zshrc"

if ! zplug check; then
  zplug install
else
  zplug update
fi

# If this file doesn't exist, zplug startup performance plummets
# https://github.com/zplug/zplug/issues/368
touch $ZPLUG_LOADFILE
